version: '3.6'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - SQLALCHEMY_DB_URL=postgresql+psycopg2://postgres:mysecret@database:5432/stay-safe
    depends_on:
      - db
    container_name: api-server
    volumes:
      - ./src:/app
    ports:
      - "8083:8083"
    restart: on-failure

  db:
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: stay-safe
    image: postgres
    container_name: database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
     - 5432:5432

