name: CI

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run build
        run: |
          docker-compose --file docker-compose.yml build

      - name: Run tests
        run: |
          docker-compose --file docker-compose.yml run api pytest
          
      - name: Analysing the code with pylint
        run: |
          docker-compose run api sh -c "pylint **/*.py"
